services:
  dashy:
    container_name: Dashy
    build: .
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    ports:
      - 9006:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
